<a href="https://colab.research.google.com/github/Gruntrexpewrus/StatLearnTeam/blob/master/Copia2_di_RedditPolarityMethod1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from nltk.stem.snowball import ItalianStemmer
from nltk import RegexpTokenizer
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
stopwords = nltk.corpus.stopwords.words("italian")
def process_text(text):
  to_return = [ItalianStemmer().stem(x) for x in RegexpTokenizer(r"\w+").tokenize(text) if not x in stopwords]
  #return (" ".join(to_return))
  return to_return

In [3]:
process_text('La Connessione di Nina fa schifo.')

['la', 'connession', 'nin', 'fa', 'schif']

In [4]:
import pandas as pd

In [5]:
wikineutral = pd.read_csv('/content/drive/My Drive/Topic detection/wiki_topics.csv', index_col = 0 , sep = "\t", encoding = "utf-8")

In [6]:
wikineutral.shape

(354, 2)

In [7]:
wikineutral.drop(wikineutral.tail(200).index, inplace = True)

In [8]:
wikineutral.shape

(154, 2)

In [9]:
wikineutral.shape

(154, 2)

In [10]:
wikineutral.head()

Topic                                               Text
0  Arte e cultura  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...
1  Arte e cultura  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...
2  Arte e cultura  Voci principali: Architettura del Settecento, ...
3  Arte e cultura  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...
4  Arte e cultura  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...

In [11]:
wikineutral.drop(['Topic'], axis = 1,  inplace = True)
wikineutral['Sentiment'] = 'neutral'

wikineutral.to_csv('/content/drive/My Drive/Topic detection/Wikineutral.csv')

In [12]:
wikineutral.head()

Text Sentiment
0  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...   neutral
1  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...   neutral
2  Voci principali: Architettura del Settecento, ...   neutral
3  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...   neutral
4  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...   neutral

In [13]:
Amazonrewiews = pd.read_csv('/content/drive/My Drive/Topic detection/TrainDataSentiment.csv', index_col = 0 )
Amazonrewiews.head()

content  rating
0  Ho acquistato questa confezione di mascherine ...       4
1  Attenzione, ha un ferretto nasale in plastica ...       1
2  La confezione di cartone era già aperta, appen...       1
3  Mascherine vendute come "Maschera Chirurgica 3...       1
4                   ARRIVATO APERTO PESSIMO PRODOTTO       1

In [14]:
Amazonrewiews['rating'] = Amazonrewiews['rating'].map({5: 'positive', 4: 'positive', 1:'negative', 2:'negative',3:'negative' })
Ama = Amazonrewiews.rename(columns={'content': 'Text', 'rating': 'Sentiment' })
Ama.head()


Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [15]:
Ama.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [16]:
Ama['Sentiment'][0]

'positive'

In [17]:
wikineutral['Sentiment'][0]

'neutral'

In [18]:
wikineutral.head()

Text Sentiment
0  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...   neutral
1  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...   neutral
2  Voci principali: Architettura del Settecento, ...   neutral
3  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...   neutral
4  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...   neutral

In [19]:
Ama.shape

(460, 2)

In [20]:
wikineutral.shape

(154, 2)

In [21]:
TrainData = pd.concat([Ama, wikineutral], ignore_index = True)

In [22]:
TrainData.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [23]:
TrainData.shape

(614, 2)

In [24]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/TrainData4SentimentLeoandNigna.csv')

In [25]:
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TrainData4SentimentLeoandNigna.csv', index_col = 0 )
TrainData.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [26]:
TrainData = TrainData.dropna()
tokenized_data = []
from tqdm import tqdm 
for index in tqdm(range(len(TrainData))):
  tokenized_data.append(" ".join(process_text(TrainData.iloc[index]["Text"])))

100%|██████████| 613/613 [00:21<00:00, 29.09it/s]


In [27]:
TrainData["Processed Text"] = tokenized_data

In [28]:
TrainData.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [29]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/ProcessedTrainData4SentimentLeoandNigna.csv')


## Let's create the bag of words **model**

In [30]:
text = ['mama is big', 'big big big fat big Nina']

In [31]:
text

['mama is big', 'big big big fat big Nina']

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(text)
X

<2x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [89]:
import joblib
joblib.dump( vectorizer, '/content/drive/My Drive/Topic detection/Vectorizer.pkl')

vectorizer_loaded = joblib.load('/content/drive/My Drive/Topic detection/Vectorizer.pkl')

In [34]:
print(vectorizer.get_feature_names())

['big', 'fat', 'is', 'mama', 'nina']


In [35]:
#a b c
#doc 1 (0,.66, 0.33) = 'b b c'

In [36]:
Y = X.toarray()

In [37]:
for i in Y:
  print(i)

[0.44943642 0.         0.6316672  0.6316672  0.        ]
[0.89553242 0.31465989 0.         0.         0.31465989]


In [38]:
TrainList = TrainData['Text'].tolist()

In [39]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(TrainList)
X #Matrix with each row TfIdf

<613x65508 sparse matrix of type '<class 'numpy.float64'>'
	with 354181 stored elements in Compressed Sparse Row format>

In [40]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import random as sparse_random
from sklearn.random_projection import sparse_random_matrix
svd = TruncatedSVD(n_components=200, n_iter=7, random_state=42)
a = svd.fit_transform(X)
a
#print(svd.explained_variance_ratio_)

##print(svd.explained_variance_ratio_.sum())

#print(svd.singular_values_) A = USV^t S singular matrix (x0000000
                                                      #      0y00000000000000000)


array([[ 2.72477921e-01,  2.19722663e-01,  2.41873042e-02, ...,
        -1.35069144e-03,  1.67971548e-03,  1.08763949e-02],
       [ 1.69086233e-01,  9.75741323e-02, -5.23767439e-03, ...,
         4.49712636e-04,  4.89908460e-03,  2.93880041e-03],
       [ 2.17972179e-01,  1.22996231e-01,  6.53177650e-02, ...,
         4.39496655e-03,  2.08280290e-03,  1.67175275e-03],
       ...,
       [ 5.46481098e-01, -1.26183255e-01,  1.04521976e-02, ...,
         1.33294738e-02,  3.66383324e-02, -1.12778499e-02],
       [ 6.07700540e-01, -1.12720598e-01,  9.94584333e-03, ...,
         3.62072962e-02,  1.28623951e-01, -9.18199482e-03],
       [ 6.00992272e-01, -1.32766560e-01,  1.02204211e-02, ...,
         4.63442622e-02,  1.62474840e-01, -1.17156283e-02]])

In [41]:
import joblib
joblib.dump( svd, '/content/drive/My Drive/Topic detection/SVD.pkl')

svd_loaded = joblib.load('/content/drive/My Drive/Topic detection/SVD.pkl')

In [42]:
len(a)

613

In [43]:
i = 0
a2 = []
for i in range(1,201):
  a2.append([])

for position in range(len(a)):
  for col in range(0,200):
    # print(a[position][col])
     a2[col].append(a[position][col])
print(len(a2))

200


In [44]:
a2[0]

[0.27247792065239457,
 0.16908623342662926,
 0.21797217894206228,
 0.07175741115385922,
 0.024622949971823467,
 0.2724779206523936,
 0.16908623342662926,
 0.21797217894206228,
 0.07175741115385922,
 0.024622949971823467,
 0.31730887373037714,
 0.30165263546476584,
 0.2193607269958688,
 0.14484141705512485,
 0.16558215726319983,
 0.24684668135791385,
 0.21473052496898498,
 0.16838216653881902,
 0.17984062567149225,
 0.14279785544457466,
 0.2724779206523936,
 0.16908623342662926,
 0.21797217894206228,
 0.07175741115385922,
 0.024622949971823467,
 0.3116903831486748,
 0.09788069581581035,
 0.14901393125612242,
 0.042930334069925406,
 0.26556571508462773,
 0.3116903831486748,
 0.09788069581581035,
 0.14901393125612242,
 0.042930334069925406,
 0.26556571508462773,
 0.3116903831486748,
 0.09788069581581035,
 0.14901393125612242,
 0.042930334069925406,
 0.26556571508462773,
 0.3116903831486748,
 0.09788069581581035,
 0.14901393125612242,
 0.042930334069925406,
 0.26556571508462773,
 0.3116903

In [45]:
l = []
for i in range(1,201):
    l.append('feat'+str(i))

In [46]:
l[0]

'feat1'

In [47]:
print(len(vectorizer.get_feature_names()))

65508


In [48]:
ff = a.tolist()

In [49]:
len(ff[0])

200

In [50]:
TrainData['TfIdfVectors'] = ff

In [51]:
TrainData['TfIdfVectors']

0      [0.27247792065239457, 0.21972266346699976, 0.0...
1      [0.16908623342662926, 0.09757413226524703, -0....
2      [0.21797217894206228, 0.12299623105572668, 0.0...
3      [0.07175741115385922, 0.03131215810517044, 0.0...
4      [0.024622949971823467, 0.07720488916191945, 0....
                             ...                        
608    [0.54536226007737, -0.1105415812214581, -0.009...
610    [0.4892127369919711, -0.10012123633633806, -0....
611    [0.546481097862738, -0.12618325455039198, 0.01...
612    [0.6077005403740513, -0.11272059821801586, 0.0...
613    [0.60099227243804, -0.13276656037670811, 0.010...
Name: TfIdfVectors, Length: 613, dtype: object

In [52]:
TrainData

Text  ...                                       TfIdfVectors
0    Ho acquistato questa confezione di mascherine ...  ...  [0.27247792065239457, 0.21972266346699976, 0.0...
1    Attenzione, ha un ferretto nasale in plastica ...  ...  [0.16908623342662926, 0.09757413226524703, -0....
2    La confezione di cartone era già aperta, appen...  ...  [0.21797217894206228, 0.12299623105572668, 0.0...
3    Mascherine vendute come "Maschera Chirurgica 3...  ...  [0.07175741115385922, 0.03131215810517044, 0.0...
4                     ARRIVATO APERTO PESSIMO PRODOTTO  ...  [0.024622949971823467, 0.07720488916191945, 0....
..                                                 ...  ...                                                ...
608  Coordinate:  06h 23m 57.109s, -52° 41′ 44.378″...  ...  [0.54536226007737, -0.1105415812214581, -0.009...
610  La Cometa Hyakutake (pronuncia giapponese: [ça...  ...  [0.4892127369919711, -0.10012123633633806, -0....
611  La cometa Shoemaker-Levy 9 (formalmente design...  ...  [0.546481097862738, -0.12618325455039198, 0.01...
612  Coordinate:  20h 20m 00s, +40° 00′ 00″\n\tIl C...  ...  [0.6077005403740513, -0.11272059821801586, 0.0...
613  Coordinate:  22h 00m 00s, +60° 00′ 00″\n\tIl c...  ...  [0.60099227243804, -0.13276656037670811, 0.010...

[613 rows x 4 columns]

In [53]:
len(a2)

200

In [54]:
j = 0
for i in l:
  TrainData[i]= a2[j]
  j = j+1

In [55]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/TfIdfData.csv')

In [56]:
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [57]:
dd = [1]*613
dd[0]

1

In [58]:
[TrainData['TfIdfVectors']].shape()

AttributeError: ignored

In [59]:
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [60]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TfIdfData.csv', index_col = 0 )
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [61]:
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

## SVM LAST STEP

In [62]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TfIdfData.csv', index_col = 0 )
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [63]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [64]:
# Seperating Predictors and Outcome values from train and test sets
X_train = TrainData.drop(['Text', 'Sentiment', 'Processed Text', 'TfIdfVectors'], axis = 1)
Y_train_label = TrainData['Sentiment']
#X_test = TrainData.drop(['Text', 'Sentiment', 'Processed Text', 'TfIdfVectors'], axis = 1)
###Y_test_label = TrainData['Sentiment']

# Dimension of Train and Test set 
print("Dimension of Train set",X_train.shape)
#print("Dimension of Test set",X_test.shape,"\n")

# Transforming non numerical labels into numerical labels
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(Y_train_label)
Y_train = encoder.transform(Y_train_label)

# encoding test labels 
#encoder.fit(Y_test_label)
#Y_test = encoder.transform(Y_test_label)

#Total Number of Continous and Categorical features in the training set
num_cols = X_train._get_numeric_data().columns
print("Number of numeric features:",num_cols.size)
#list(set(X_train.columns) - set(num_cols))


names_of_predictors = list(X_train.columns.values)

# Scaling the Train and Test feature set 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
#X_test_scaled = scaler.transform(X_test)

Dimension of Train set (613, 200)
Number of numeric features: 200


In [65]:
Y_train

array([2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0,
       0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2,
       0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0,
       0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0,
       2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2,

In [66]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate

final_model = SVC()
final_model.fit(X_train_scaled, Y_train)
scores = cross_val_score(final_model ,X_train_scaled, Y_train,
                       scoring='accuracy', cv = 6)

In [67]:
scores.mean()


0.69346087949743

In [68]:
#Libraries to Build Ensemble Model : Random Forest Classifier 
# Create the parameter grid based on the results of random search 
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [ 1000]},
                    {'kernel': ['linear'], 'C': [ 1000]}]

In [69]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5)
svm_model.fit(X_train_scaled, Y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1000], 'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [70]:
final_model = svm_model.best_estimator_
Y_pred = final_model.predict(X_test_scaled)
Y_pred_label = list(encoder.inverse_transform(Y_pred))

NameError: ignored

In [71]:
print(confusion_matrix(Y_test_label,Y_pred_label))
print("\n")
print(classification_report(Y_test_label,Y_pred_label))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled , Y_train))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled  , Y_test ))

svm_model.score

NameError: ignored

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text', 'TfIdfVectors'], axis = 1),
TrainData['Sentiment'], test_size=0.3, random_state=42)

In [75]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(y_train2)
Y_train2 = encoder.transform(y_train2)

encoder = preprocessing.LabelEncoder()

# encoding y_test2 labels 
encoder.fit(y_test2)
Y_test2 = encoder.transform(y_test2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)

scaler = StandardScaler()
X_test_scaled2 = scaler.fit_transform(X_test2)


In [76]:
Y_test2

array([2, 2, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 1, 0, 1, 2, 0, 0, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0,
       0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0,
       1, 2, 1, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 1,
       0, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0,
       2, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 2, 1, 2, 1, 2, 2, 2, 2, 0, 2, 0,
       2, 2, 2, 1, 0, 2, 1, 2, 2, 1, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 0, 2,
       1, 0, 0, 2, 0, 1, 1, 2])

In [77]:
params_grid = [{'kernel': ['rbf', 'poly', 'linear', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                     'C': [10, 20, 50, 100, 200]} ]

In [78]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
svm_model.fit(X_train_scaled2, y_train2)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    5.1s
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    5.1s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    5.2s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    5.4s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    5.5s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    5.6s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    5.7s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    5.7s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    6.0s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    6.1s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    6.1s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    6.3s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:  

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=12,
             param_grid=[{'C': [10, 20, 50, 100, 200],
                          'gamma': [0.005, 0.0003, 1e-05],
                          'kernel': ['rbf', 'poly', 'linear', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=12)

In [80]:
svm_model.best_params_

{'C': 10, 'gamma': 0.0003, 'kernel': 'sigmoid'}

In [81]:
final_model = svm_model.best_estimator_
final_model

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0003, kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [82]:
Y_pred = final_model.predict(X_test_scaled2)
#Y_pred_label = list(encoder.inverse_transform(Y_pred))
#Y_pred is cathegorical

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled2  , y_test2 ))

svm_model.score

[[55  0  4]
 [ 0 41  0]
 [10  0 74]]


              precision    recall  f1-score   support

    negative       0.85      0.93      0.89        59
     neutral       1.00      1.00      1.00        41
    positive       0.95      0.88      0.91        84

    accuracy                           0.92       184
   macro avg       0.93      0.94      0.93       184
weighted avg       0.93      0.92      0.92       184

Training set score for SVM: 1.000000
Testing  set score for SVM: 0.923913


<bound method BaseSearchCV.score of GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=12,
             param_grid=[{'C': [10, 20, 50, 100, 200],
                          'gamma': [0.005, 0.0003, 1e-05],
                          'kernel': ['rbf', 'poly', 'linear', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=12)>

In [83]:
#how to save a model
import joblib
joblib.dump( final_model, '/content/drive/My Drive/Topic detection/firstSVM.pkl')

my_model_loaded = joblib.load('/content/drive/My Drive/Topic detection/firstSVM.pkl')

In [84]:
my_model_loaded

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0003, kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [85]:
from sklearn.naive_bayes import GaussianNB

In [86]:
# Gaussian assumption

gnb = GaussianNB()
Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % gnb.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % gnb.score(X_test_scaled2  , y_test2 ))

gnb.score

[[45  0 14]
 [ 0 41  0]
 [45  4 35]]


              precision    recall  f1-score   support

    negative       0.50      0.76      0.60        59
     neutral       0.91      1.00      0.95        41
    positive       0.71      0.42      0.53        84

    accuracy                           0.66       184
   macro avg       0.71      0.73      0.69       184
weighted avg       0.69      0.66      0.65       184

Training set score for SVM: 0.696970
Testing  set score for SVM: 0.586957


<bound method ClassifierMixin.score of GaussianNB(priors=None, var_smoothing=1e-09)>

In [87]:
# bernoulli
from sklearn.naive_bayes import BernoulliNB
#>>> clf = BernoulliNB()
gnb =   BernoulliNB()
Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for BNB: %f" % gnb.score(X_train_scaled2 , y_train2))
print("Testing  set score for BNB: %f" % gnb.score(X_test_scaled2  , y_test2 ))

gnb.score

[[43  0 16]
 [ 0 38  3]
 [13  3 68]]


              precision    recall  f1-score   support

    negative       0.77      0.73      0.75        59
     neutral       0.93      0.93      0.93        41
    positive       0.78      0.81      0.80        84

    accuracy                           0.81       184
   macro avg       0.83      0.82      0.82       184
weighted avg       0.81      0.81      0.81       184

Training set score for BNB: 0.864802
Testing  set score for BNB: 0.755435


<bound method ClassifierMixin.score of BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)>

In [88]:
from sklearn.metrics import accuracy_score
#print accuracy_score(pred, labels_test)
accuracy_score(Y_pred ,y_test2)

0.8097826086956522