<a href="https://colab.research.google.com/github/Gruntrexpewrus/StatLearnTeam/blob/master/which_is_the_best.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from nltk.stem.snowball import ItalianStemmer
from nltk import RegexpTokenizer
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
stopwords = nltk.corpus.stopwords.words("italian")
def process_text(text):
  to_return = [ItalianStemmer().stem(x) for x in RegexpTokenizer(r"\w+").tokenize(text) if not x in stopwords]
  #return (" ".join(to_return))
  return to_return

In [ ]:
process_text('La Connessione di Nina fa schifo.')

['la', 'connession', 'nin', 'fa', 'schif']

In [ ]:
import pandas as pd

In [ ]:
wikineutral = pd.read_csv('/content/drive/My Drive/Topic detection/wiki_topics.csv', index_col = 0 , sep = "\t", encoding = "utf-8")

In [ ]:
wikineutral.shape

(354, 2)

In [ ]:
wikineutral.drop(wikineutral.tail(200).index, inplace = True)

In [ ]:
wikineutral.shape

(154, 2)

In [ ]:
wikineutral.shape

(154, 2)

In [ ]:
wikineutral.head()

Topic                                               Text
0  Arte e cultura  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...
1  Arte e cultura  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...
2  Arte e cultura  Voci principali: Architettura del Settecento, ...
3  Arte e cultura  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...
4  Arte e cultura  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...

In [ ]:
wikineutral.drop(['Topic'], axis = 1,  inplace = True)
wikineutral['Sentiment'] = 'neutral'

wikineutral.to_csv('/content/drive/My Drive/Topic detection/Wikineutral.csv')

In [ ]:
wikineutral.head()

Text Sentiment
0  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...   neutral
1  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...   neutral
2  Voci principali: Architettura del Settecento, ...   neutral
3  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...   neutral
4  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...   neutral

In [ ]:
Amazonrewiews = pd.read_csv('/content/drive/My Drive/Topic detection/TrainDataSentiment.csv', index_col = 0 )
Amazonrewiews.head()

content  rating
0  Ho acquistato questa confezione di mascherine ...       4
1  Attenzione, ha un ferretto nasale in plastica ...       1
2  La confezione di cartone era già aperta, appen...       1
3  Mascherine vendute come "Maschera Chirurgica 3...       1
4                   ARRIVATO APERTO PESSIMO PRODOTTO       1

In [ ]:
Amazonrewiews['rating'] = Amazonrewiews['rating'].map({5: 'positive', 4: 'positive', 1:'negative', 2:'negative',3:'negative' })
Ama = Amazonrewiews.rename(columns={'content': 'Text', 'rating': 'Sentiment' })
Ama.head()


Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [ ]:
Ama.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [ ]:
Ama['Sentiment'][0]

'positive'

In [ ]:
wikineutral['Sentiment'][0]

'neutral'

In [ ]:
wikineutral.head()

Text Sentiment
0  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...   neutral
1  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...   neutral
2  Voci principali: Architettura del Settecento, ...   neutral
3  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...   neutral
4  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...   neutral

In [ ]:
Ama.shape

(460, 2)

In [ ]:
wikineutral.shape

(154, 2)

In [ ]:
TrainData = pd.concat([Ama, wikineutral], ignore_index = True)

In [ ]:
TrainData.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [ ]:
TrainData.shape

(614, 2)

In [ ]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/TrainData4SentimentLeoandNigna.csv')

In [ ]:
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TrainData4SentimentLeoandNigna.csv', index_col = 0 )
TrainData.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [ ]:
TrainData = TrainData.dropna()
tokenized_data = []
from tqdm import tqdm 
for index in tqdm(range(len(TrainData))):
  tokenized_data.append(" ".join(process_text(TrainData.iloc[index]["Text"])))

100%|██████████| 613/613 [00:21<00:00, 29.09it/s]


In [ ]:
TrainData["Processed Text"] = tokenized_data

In [ ]:
TrainData.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [ ]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/ProcessedTrainData4SentimentLeoandNigna.csv')


## Let's create the tftidf model

---



In [38]:
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/ProcessedTrainData4SentimentLeoandNigna.csv', index_col = 0 )

In [ ]:
TrainData.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [ ]:
for i in Y:
  print(i)

[0.44943642 0.         0.6316672  0.6316672  0.        ]
[0.89553242 0.31465989 0.         0.         0.31465989]


In [39]:
TrainList = TrainData['Processed Text'].tolist()

In [ ]:
TrainList[0]

'ho acquist confezion mascherin 19 99 quind 40 centesim mascherin prezz somm onest la qualit mascherin avvis discret prov altre consistt indubb maggior risult tatt morbid spess nell confezion present certific cines attest tipolog iir gli elast manteng molt ben già utilizz 5 senz nessun problem ven difett essenzial due 1 mascherin chius scatol senz imball isol nessun plastic protezion 2 ferrett string nas sembr esser metall quind pieg ben senz raggiung chiusur massim'

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(TrainList)

X #Matrix with each row TfIdf

<613x38013 sparse matrix of type '<class 'numpy.int64'>'
	with 267849 stored elements in Compressed Sparse Row format>

In [ ]:
import joblib
joblib.dump( vectorizer, '/content/drive/My Drive/Topic detection/Vectorizer.pkl')

vectorizer_loaded = joblib.load('/content/drive/My Drive/Topic detection/Vectorizer.pkl')

In [ ]:
# SVD in 100/200/300 components

In [42]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import random as sparse_random
from sklearn.random_projection import sparse_random_matrix
import joblib
comps = [100, 200, 300]
def Svd(comps):
  SVDMatrices = []
  for i in comps:
    svd = TruncatedSVD(n_components=i, n_iter=7, random_state=42)
    a = svd.fit_transform(X)
    SVDMatrices.append(a)
    joblib.dump( svd, '/content/drive/My Drive/Topic detection/SVD'+str(i)+'.pkl')
    print(comps, svd.explained_variance_ratio_.sum())
  return (SVDMatrices)
#print(svd.explained_variance_ratio_)



#print(svd.singular_values_) A = USV^t S singular matrix (x0000000
                                                      #      0y00000000000000000)


In [43]:
SVDMatrices = Svd(comps)

[100, 200, 300] 0.9430592092080162
[100, 200, 300] 0.9989350597501335
[100, 200, 300] 0.9999170949846715


In [44]:
#len(SVDMatrices[0][0][612])
len(SVDMatrices[0])

613

In [45]:
def namescreator(matrices = SVDMatrices):
  names = []
 # print(len(names))
  for j in range(0,len(matrices)):
      names.append([])
  for i in range(len(matrices)):
   #   print(i)
     # print(len(matrices[i]))
      ln = len(matrices[i][0])
     # print(ln)
     # print(names)
      temp = []
      for j in range(0,len(matrices[i][0])):
         temp.append([])
      print(len(temp))
      for position in range(len(matrices[i][0])):
       # print(position)
        for row in range(613):
       #  print(a[position][col])
        # print(range(ln-1))
         temp[position].append(matrices[i][row][position])
      for k in temp:
       names[i].append(k)

  return names
#print(len(a[0]))

In [46]:
ttry = namescreator([SVDMatrices[1]])
len(ttry[0])

200


200

In [ ]:
len(ttry)

3

In [47]:
l = []
for i in range(3):
  l.append([])
for i in range(1,101):
    l[0].append('feat'+str(i))
for i in range(1,201):
    l[1].append('feat'+str(i))
for i in range(1,301):
    l[2].append('feat'+str(i))

In [ ]:
len(l[2])

300

In [48]:
#I have a list with 3 components and in every one 100/200/300 columns
#I have a set of names
df100 = TrainData.copy()
df200 = TrainData.copy()
df300 = TrainData.copy()

In [49]:
def datafinal(l, a2, df):
  j = 0
  for i in l:
  #  print(len(a2[j]))
    df[i]= a2[j]
    j = j+1
  return df

In [50]:
df100 = datafinal(l[0], namescreator([SVDMatrices[0]])[0], df100 )
df200 = datafinal(l[1], namescreator([SVDMatrices[1]])[0], df200 )
df300 = datafinal(l[2], namescreator([SVDMatrices[2]])[0], df300 )

df100.to_csv('/content/drive/My Drive/Topic detection/Df_count_100.csv')
df200.to_csv('/content/drive/My Drive/Topic detection/Df_count_200.csv')
df300.to_csv('/content/drive/My Drive/Topic detection/Df_count_300.csv')
df100.head()


100
200
300


Text  ...   feat100
0  Ho acquistato questa confezione di mascherine ...  ... -0.003686
1  Attenzione, ha un ferretto nasale in plastica ...  ... -0.023857
2  La confezione di cartone era già aperta, appen...  ... -0.014728
3  Mascherine vendute come "Maschera Chirurgica 3...  ... -0.057438
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ... -0.044963

[5 rows x 103 columns]

In [ ]:
len(df300.columns)

303

In [ ]:
df100.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [ ]:
len(l[0])
len(namescreator([SVDMatrices[0]])[0])

100


100

In [ ]:
df1

Text  ...                                     Processed Text
0    Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1    Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2    La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3    Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                     ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott
..                                                 ...  ...                                                ...
608  Coordinate:  06h 23m 57.109s, -52° 41′ 44.378″...  ...  coordin 06h 23m 57 109s 52 41 44 378 canop afi...
610  La Cometa Hyakutake (pronuncia giapponese: [ça...  ...  la comet hyakutak pronunc giappones çakɯtak de...
611  La cometa Shoemaker-Levy 9 (formalmente design...  ...  la comet shoemaker levy 9 formal design 1993e ...
612  Coordinate:  20h 20m 00s, +40° 00′ 00″\n\tIl C...  ...  coordin 20h 20m 00s 40 00 00 il compless nebul...
613  Coordinate:  22h 00m 00s, +60° 00′ 00″\n\tIl c...  ...  coordin 22h 00m 00s 60 00 00 il compless nebul...

[613 rows x 3 columns]

In [ ]:
print(len(vectorizer.get_feature_names()))

65508


In [ ]:
ff = a.tolist()

In [ ]:
len(ff[0])

200

In [ ]:
TrainData['TfIdfVectors'] = ff

In [ ]:
TrainData['TfIdfVectors']

0      [0.27247792065239457, 0.21972266346699976, 0.0...
1      [0.16908623342662926, 0.09757413226524703, -0....
2      [0.21797217894206228, 0.12299623105572668, 0.0...
3      [0.07175741115385922, 0.03131215810517044, 0.0...
4      [0.024622949971823467, 0.07720488916191945, 0....
                             ...                        
608    [0.54536226007737, -0.1105415812214581, -0.009...
610    [0.4892127369919711, -0.10012123633633806, -0....
611    [0.546481097862738, -0.12618325455039198, 0.01...
612    [0.6077005403740513, -0.11272059821801586, 0.0...
613    [0.60099227243804, -0.13276656037670811, 0.010...
Name: TfIdfVectors, Length: 613, dtype: object

In [ ]:
TrainData

Text  ...                                       TfIdfVectors
0    Ho acquistato questa confezione di mascherine ...  ...  [0.27247792065239457, 0.21972266346699976, 0.0...
1    Attenzione, ha un ferretto nasale in plastica ...  ...  [0.16908623342662926, 0.09757413226524703, -0....
2    La confezione di cartone era già aperta, appen...  ...  [0.21797217894206228, 0.12299623105572668, 0.0...
3    Mascherine vendute come "Maschera Chirurgica 3...  ...  [0.07175741115385922, 0.03131215810517044, 0.0...
4                     ARRIVATO APERTO PESSIMO PRODOTTO  ...  [0.024622949971823467, 0.07720488916191945, 0....
..                                                 ...  ...                                                ...
608  Coordinate:  06h 23m 57.109s, -52° 41′ 44.378″...  ...  [0.54536226007737, -0.1105415812214581, -0.009...
610  La Cometa Hyakutake (pronuncia giapponese: [ça...  ...  [0.4892127369919711, -0.10012123633633806, -0....
611  La cometa Shoemaker-Levy 9 (formalmente design...  ...  [0.546481097862738, -0.12618325455039198, 0.01...
612  Coordinate:  20h 20m 00s, +40° 00′ 00″\n\tIl C...  ...  [0.6077005403740513, -0.11272059821801586, 0.0...
613  Coordinate:  22h 00m 00s, +60° 00′ 00″\n\tIl c...  ...  [0.60099227243804, -0.13276656037670811, 0.010...

[613 rows x 4 columns]

In [ ]:
len(a2)

200

In [ ]:
j = 0
for i in l:
  TrainData[i]= a2[j]
  j = j+1

In [ ]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/TfIdfData.csv')

In [ ]:
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [ ]:
dd = [1]*613
dd[0]

1

In [ ]:
[TrainData['TfIdfVectors']].shape()

AttributeError: ignored

In [ ]:
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [ ]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TfIdfData.csv', index_col = 0 )
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [ ]:
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

## Find the best

In [4]:
import pandas as pd

In [13]:
df100 = pd.read_csv('/content/drive/My Drive/Topic detection/Df100.csv', index_col=0)
df200 = pd.read_csv('/content/drive/My Drive/Topic detection/Df200.csv', index_col=0)
df300 = pd.read_csv('/content/drive/My Drive/Topic detection/Df300.csv', index_col=0)


In [6]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [24]:
def SVM_model(TrainData):

    X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
    TrainData['Sentiment'], test_size=0.3, random_state=42)

    from sklearn import preprocessing
    encoder = preprocessing.LabelEncoder()

    # encoding train labels 
    encoder.fit(y_train2)
    Y_train2 = encoder.transform(y_train2)

    encoder = preprocessing.LabelEncoder()

    # encoding y_test2 labels 
    encoder.fit(y_test2)
    Y_test2 = encoder.transform(y_test2)

    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    X_train_scaled2 = scaler.fit_transform(X_train2)

    scaler = StandardScaler()
    X_test_scaled2 = scaler.fit_transform(X_test2)


    params_grid = [{'kernel': ['rbf', 'poly', 'linear', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                        'C': [10, 20, 50, 100, 200]} ]



    svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
    svm_model.fit(X_train_scaled2, y_train2)


    final_model = svm_model.best_estimator_

    Y_pred = final_model.predict(X_test_scaled2)
    #Y_pred_label = list(encoder.inverse_transform(Y_pred))
    #Y_pred is cathegorical

    print(confusion_matrix(y_test2,Y_pred))
    print("\n")
    print(classification_report(y_test2,Y_pred))

    print("Training set score for SVM: %f" % final_model.score(X_train_scaled2 , y_train2))
    print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled2  , y_test2 ))
    from sklearn.metrics import accuracy_score

    return(accuracy_score(Y_pred ,y_test2))
    #svm_model.score


In [34]:
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import BernoulliNB
def bernouli(TrainData):

    X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
    TrainData['Sentiment'], test_size=0.3, random_state=42)

    from sklearn import preprocessing
    encoder = preprocessing.LabelEncoder()

    # encoding train labels 
    encoder.fit(y_train2)
    Y_train2 = encoder.transform(y_train2)

    encoder = preprocessing.LabelEncoder()

    # encoding y_test2 labels 
    encoder.fit(y_test2)
    Y_test2 = encoder.transform(y_test2)

    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    X_train_scaled2 = scaler.fit_transform(X_train2)

    scaler = StandardScaler()
    X_test_scaled2 = scaler.fit_transform(X_test2)

    gnb =   BernoulliNB()
    Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

    print(confusion_matrix(y_test2,Y_pred))
    print("\n")
    print(classification_report(y_test2,Y_pred))

    print("Training set score for BNB: %f" % gnb.score(X_train_scaled2 , y_train2))
    print("Testing  set score for BNB: %f" % gnb.score(X_test_scaled2  , y_test2 ))
    return(accuracy_score(Y_pred ,y_test2))


In [51]:
from sklearn.naive_bayes import MultinomialNB


def multinomial(TrainData):

    X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
    TrainData['Sentiment'], test_size=0.3, random_state=42)

    from sklearn import preprocessing
    encoder = preprocessing.LabelEncoder()

    # encoding train labels 
    encoder.fit(y_train2)
    Y_train2 = encoder.transform(y_train2)

    encoder = preprocessing.LabelEncoder()

    # encoding y_test2 labels 
    encoder.fit(y_test2)
    Y_test2 = encoder.transform(y_test2)

    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    X_train_scaled2 = scaler.fit_transform(X_train2)

    scaler = StandardScaler()
    X_test_scaled2 = scaler.fit_transform(X_test2)

    
    clf = MultinomialNB()
    Y_pred = clf.fit(X_train2, y_train2).predict(X_test2)
    Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

    print(confusion_matrix(y_test2,Y_pred))
    print("\n")
    print(classification_report(y_test2,Y_pred))

    print("Training set score for BNB: %f" % gnb.score(X_train_scaled2 , y_train2))
    print("Testing  set score for BNB: %f" % gnb.score(X_test_scaled2  , y_test2 ))
    return(accuracy_score(Y_pred ,y_test2))


In [35]:
svm_scores=[]
docs = [df100,df200,df300]
for i in docs:
  svm_scores.append(SVM_model(i))


Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    4.9s
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    5.0s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    5.3s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    5.3s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    5.4s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    5.4s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    5.5s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    5.6s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    5.6s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    5.7s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    5.8s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:  

[[55  0  4]
 [ 0 41  0]
 [ 8  1 75]]


              precision    recall  f1-score   support

    negative       0.87      0.93      0.90        59
     neutral       0.98      1.00      0.99        41
    positive       0.95      0.89      0.92        84

    accuracy                           0.93       184
   macro avg       0.93      0.94      0.94       184
weighted avg       0.93      0.93      0.93       184

Training set score for SVM: 1.000000
Testing  set score for SVM: 0.929348
Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    0.4s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    0.4s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    0.4s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    0.6s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    0.6s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    0.6s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    0.6s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:    0.7s
[Parallel(n_jobs=12)]: Done  16 tasks      | elapsed:    0.7s
[Parallel(n_jobs=12)]: Done  17 tasks      | elapsed:    0.7s
[Paralle

[[55  0  4]
 [ 1 40  0]
 [14  1 69]]


              precision    recall  f1-score   support

    negative       0.79      0.93      0.85        59
     neutral       0.98      0.98      0.98        41
    positive       0.95      0.82      0.88        84

    accuracy                           0.89       184
   macro avg       0.90      0.91      0.90       184
weighted avg       0.90      0.89      0.89       184

Training set score for SVM: 0.997669
Testing  set score for SVM: 0.891304
Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Batch computation too fast (0.1812s.) Setting batch_size=2.
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    0.6s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    0.8s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    0.8s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    0.8s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    0.8s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    0.9s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    0.9s
[Parallel(n_jobs=12)]: Done  15 tasks      | elap

[[53  6  0]
 [ 0 41  0]
 [ 3  7 74]]


              precision    recall  f1-score   support

    negative       0.95      0.90      0.92        59
     neutral       0.76      1.00      0.86        41
    positive       1.00      0.88      0.94        84

    accuracy                           0.91       184
   macro avg       0.90      0.93      0.91       184
weighted avg       0.93      0.91      0.92       184

Training set score for SVM: 1.000000
Testing  set score for SVM: 0.913043


In [31]:
svm_scores

[0.9293478260869565, 0.8913043478260869, 0.9130434782608695]

In [36]:
bernouli_scores=[]
docs = [df100,df200,df300]
for i in docs:
  bernouli_scores.append(bernouli(i))

[[44  0 15]
 [ 2 36  3]
 [21  2 61]]


              precision    recall  f1-score   support

    negative       0.66      0.75      0.70        59
     neutral       0.95      0.88      0.91        41
    positive       0.77      0.73      0.75        84

    accuracy                           0.77       184
   macro avg       0.79      0.78      0.79       184
weighted avg       0.77      0.77      0.77       184

Training set score for BNB: 0.864802
Testing  set score for BNB: 0.750000
[[42  0 17]
 [ 3 34  4]
 [19  5 60]]


              precision    recall  f1-score   support

    negative       0.66      0.71      0.68        59
     neutral       0.87      0.83      0.85        41
    positive       0.74      0.71      0.73        84

    accuracy                           0.74       184
   macro avg       0.76      0.75      0.75       184
weighted avg       0.74      0.74      0.74       184

Training set score for BNB: 0.885781
Testing  set score for BNB: 0.739130
[[43  0 16]


In [37]:
bernouli_scores

[0.7663043478260869, 0.7391304347826086, 0.7608695652173914]

In [52]:
df_2_100 = pd.read_csv('/content/drive/My Drive/Topic detection/Df_count_100.csv', index_col=0)
df_2_200 = pd.read_csv('/content/drive/My Drive/Topic detection/Df_count_200.csv', index_col=0)
df_2_300 = pd.read_csv('/content/drive/My Drive/Topic detection/Df_count_300.csv', index_col=0)

In [53]:
multinomial_scores=[]
docs = [df_2_100,df_2_200,df_2_300]
for i in docs:
  multinomial_scores.append(multinomial(i))

ValueError: ignored

In [ ]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TfIdfData.csv', index_col = 0 )
TrainData.head()

Text  ...   feat200
0  Ho acquistato questa confezione di mascherine ...  ...  0.010876
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.002939
2  La confezione di cartone era già aperta, appen...  ...  0.001672
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.002367
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.000338

[5 rows x 204 columns]

In [ ]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
# Seperating Predictors and Outcome values from train and test sets
X_train = TrainData.drop(['Text', 'Sentiment', 'Processed Text', 'TfIdfVectors'], axis = 1)
Y_train_label = TrainData['Sentiment']
#X_test = TrainData.drop(['Text', 'Sentiment', 'Processed Text', 'TfIdfVectors'], axis = 1)
###Y_test_label = TrainData['Sentiment']

# Dimension of Train and Test set 
print("Dimension of Train set",X_train.shape)
#print("Dimension of Test set",X_test.shape,"\n")

# Transforming non numerical labels into numerical labels
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(Y_train_label)
Y_train = encoder.transform(Y_train_label)

# encoding test labels 
#encoder.fit(Y_test_label)
#Y_test = encoder.transform(Y_test_label)

#Total Number of Continous and Categorical features in the training set
num_cols = X_train._get_numeric_data().columns
print("Number of numeric features:",num_cols.size)
#list(set(X_train.columns) - set(num_cols))


names_of_predictors = list(X_train.columns.values)

# Scaling the Train and Test feature set 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
#X_test_scaled = scaler.transform(X_test)



params_grid = [{'kernel': ['rbf', 'poly', 'linear', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                     'C': [10, 20, 50, 100, 200]} ]


svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
svm_model.fit(X_train_scaled2, y_train2)


final_model = svm_model.best_estimator_

Dimension of Train set (613, 200)
Number of numeric features: 200


In [ ]:
X_train_scaled[0]

array([-0.2422465 ,  1.06273577,  0.14596816, -0.20044762, -0.58806611,
        0.3546995 , -1.31027444, -0.17867182,  0.09544826, -1.34105118,
       -2.42736216, -1.07455485,  0.74679558, -0.24535081, -0.79736548,
        0.52641408,  0.68902197, -0.05423255, -0.15217317, -0.82494248,
        0.4384681 ,  0.39283499, -0.61098823,  0.56139277,  1.14019803,
       -0.14157163,  0.37484142, -0.47070309,  0.6647269 ,  0.93577383,
        0.09128176,  1.27978683,  1.91193469,  0.19150933,  3.44042173,
        2.44449447,  0.42726319, -1.31939927, -0.92619131,  0.75864173,
        1.01092126, -1.23392566, -0.32188437, -0.84495255,  0.67143935,
        0.83310585,  0.45586204,  0.19260102,  0.18671166, -2.32332379,
        1.70157259, -0.67679777,  0.41053165, -0.60302596,  0.82494123,
       -3.56854759, -0.97368057, -0.66613718, -0.11145581,  0.80572792,
        0.52326716, -0.08439002,  0.77407631,  1.55084183, -0.86804117,
       -1.45160506,  1.48085139, -1.68969227,  0.69916784,  1.12

In [ ]:
Y_train

array([2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0,
       0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2,
       0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0,
       0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0,
       2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2,

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate

final_model = SVC()
final_model.fit(X_train_scaled, Y_train)
scores = cross_val_score(final_model ,X_train_scaled, Y_train,
                       scoring='accuracy', cv = 6)

In [ ]:
scores.mean()


0.69346087949743

In [ ]:
#Libraries to Build Ensemble Model : Random Forest Classifier 
# Create the parameter grid based on the results of random search 
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [ 1000]},
                    {'kernel': ['linear'], 'C': [ 1000]}]

In [ ]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5)
svm_model.fit(X_train_scaled, Y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1000], 'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
final_model = svm_model.best_estimator_
Y_pred = final_model.predict(X_test_scaled)
Y_pred_label = list(encoder.inverse_transform(Y_pred))

NameError: ignored

In [ ]:
print(confusion_matrix(Y_test_label,Y_pred_label))
print("\n")
print(classification_report(Y_test_label,Y_pred_label))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled , Y_train))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled  , Y_test ))

svm_model.score

NameError: ignored

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text', 'TfIdfVectors'], axis = 1),
TrainData['Sentiment'], test_size=0.3, random_state=42)

In [ ]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(y_train2)
Y_train2 = encoder.transform(y_train2)

encoder = preprocessing.LabelEncoder()

# encoding y_test2 labels 
encoder.fit(y_test2)
Y_test2 = encoder.transform(y_test2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)

scaler = StandardScaler()
X_test_scaled2 = scaler.fit_transform(X_test2)


In [ ]:
Y_test2

array([2, 2, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 1, 0, 1, 2, 0, 0, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0,
       0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0,
       1, 2, 1, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 1,
       0, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0,
       2, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 2, 1, 2, 1, 2, 2, 2, 2, 0, 2, 0,
       2, 2, 2, 1, 0, 2, 1, 2, 2, 1, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 0, 2,
       1, 0, 0, 2, 0, 1, 1, 2])

In [ ]:
params_grid = [{'kernel': ['rbf', 'poly', 'linear', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                     'C': [10, 20, 50, 100, 200]} ]

In [ ]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
svm_model.fit(X_train_scaled2, y_train2)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    5.1s
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    5.1s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    5.2s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    5.4s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    5.5s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    5.6s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    5.7s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    5.7s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    6.0s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    6.1s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    6.1s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    6.3s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:  

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=12,
             param_grid=[{'C': [10, 20, 50, 100, 200],
                          'gamma': [0.005, 0.0003, 1e-05],
                          'kernel': ['rbf', 'poly', 'linear', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=12)

In [ ]:
svm_model.best_params_

{'C': 10, 'gamma': 0.0003, 'kernel': 'sigmoid'}

In [ ]:
final_model = svm_model.best_estimator_
final_model

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0003, kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
Y_pred = final_model.predict(X_test_scaled2)
#Y_pred_label = list(encoder.inverse_transform(Y_pred))
#Y_pred is cathegorical

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled2  , y_test2 ))

svm_model.score

[[55  0  4]
 [ 0 41  0]
 [10  0 74]]


              precision    recall  f1-score   support

    negative       0.85      0.93      0.89        59
     neutral       1.00      1.00      1.00        41
    positive       0.95      0.88      0.91        84

    accuracy                           0.92       184
   macro avg       0.93      0.94      0.93       184
weighted avg       0.93      0.92      0.92       184

Training set score for SVM: 1.000000
Testing  set score for SVM: 0.923913


<bound method BaseSearchCV.score of GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=12,
             param_grid=[{'C': [10, 20, 50, 100, 200],
                          'gamma': [0.005, 0.0003, 1e-05],
                          'kernel': ['rbf', 'poly', 'linear', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=12)>

In [ ]:
#how to save a model
import joblib
joblib.dump( final_model, '/content/drive/My Drive/Topic detection/firstSVM.pkl')

my_model_loaded = joblib.load('/content/drive/My Drive/Topic detection/firstSVM.pkl')

In [ ]:
my_model_loaded

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0003, kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
# Gaussian assumption

gnb = GaussianNB()
Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % gnb.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % gnb.score(X_test_scaled2  , y_test2 ))

gnb.score

[[45  0 14]
 [ 0 41  0]
 [45  4 35]]


              precision    recall  f1-score   support

    negative       0.50      0.76      0.60        59
     neutral       0.91      1.00      0.95        41
    positive       0.71      0.42      0.53        84

    accuracy                           0.66       184
   macro avg       0.71      0.73      0.69       184
weighted avg       0.69      0.66      0.65       184

Training set score for SVM: 0.696970
Testing  set score for SVM: 0.586957


<bound method ClassifierMixin.score of GaussianNB(priors=None, var_smoothing=1e-09)>

In [ ]:
# bernoulli
from sklearn.naive_bayes import BernoulliNB

gnb =   BernoulliNB()
Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for BNB: %f" % gnb.score(X_train_scaled2 , y_train2))
print("Testing  set score for BNB: %f" % gnb.score(X_test_scaled2  , y_test2 ))

gnb.score

[[43  0 16]
 [ 0 38  3]
 [13  3 68]]


              precision    recall  f1-score   support

    negative       0.77      0.73      0.75        59
     neutral       0.93      0.93      0.93        41
    positive       0.78      0.81      0.80        84

    accuracy                           0.81       184
   macro avg       0.83      0.82      0.82       184
weighted avg       0.81      0.81      0.81       184

Training set score for BNB: 0.864802
Testing  set score for BNB: 0.755435


<bound method ClassifierMixin.score of BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)>

In [ ]:
from sklearn.metrics import accuracy_score
#print accuracy_score(pred, labels_test)
accuracy_score(Y_pred ,y_test2)

0.8097826086956522

In [ ]:
#Do multinomial